name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force

      - name: Compile Feather
        run: | 
          mkdir -p Zsign
          echo "MIT License" > Zsign/LICENSE_LC
          agvtool new-version -all $(git rev-parse HEAD)
          xcodebuild -resolvePackageDependencies -workspace Feather.xcworkspace -scheme Feather
          make
          mkdir upload
          mv packages/* upload/

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" _build/Payload/*.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
